// SPDX-License-Identifier: GPL-2.0-or-later
// nrsk split keyboard - default keymap (generated by gen/make_qmk.py)
// Unlabeled keys in the KLE layout are KC_NO; assign them as you like.
#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_ESC  , KC_F1   , KC_F2   , KC_F3   , KC_F4   , KC_F5   , KC_F6   , KC_NO,
        KC_GRV  , KC_1    , KC_2    , KC_3    , KC_4    , KC_5    , KC_6    , KC_NO,
        KC_TAB  , KC_Q    , KC_W    , KC_E    , KC_R    , KC_T    , KC_NO,
        KC_LCTL , KC_A    , KC_S    , KC_D    , KC_F    , KC_G    , KC_NO,
        KC_LSFT , KC_Z    , KC_X    , KC_C    , KC_V    , KC_B    , KC_NO,
        KC_LCTL , KC_LALT , KC_LGUI , KC_SPC  , KC_SPC  , KC_SPC  , KC_NO,
        KC_NO   , KC_F7   , KC_F8   , KC_F9   , KC_F10  , KC_F11  , KC_F12,
        KC_NO   , KC_7    , KC_8    , KC_9    , KC_0    , KC_MINS , KC_EQL  , KC_BSPC,
        KC_NO   , KC_Y    , KC_U    , KC_I    , KC_O    , KC_P    , KC_LBRC , KC_RBRC , KC_BSLS,
        KC_NO   , KC_H    , KC_J    , KC_K    , KC_L    , KC_SCLN , KC_QUOT , KC_ENT,
        KC_NO   , KC_N    , KC_M    , KC_COMM , KC_DOT  , KC_SLSH , KC_UP   , MO(1),
        KC_NO   , KC_SPC  , KC_SPC  , KC_RGUI , KC_RALT , KC_LEFT , KC_DOWN , KC_RGHT
    ),
    [1] = LAYOUT(
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_ESC  , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_DEL,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_PGUP , KC_TRNS,
        KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_HOME , KC_PGDN , KC_END
    )
};


#ifdef OLED_ENABLE
// 0.91" 128x32 OLED mounted vertically on both halves
oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_270;
}

static void render_status(void) {
    oled_write_ln_P(PSTR("nrsk"), false);
    oled_write_ln_P(PSTR(""), false);
    oled_write_P(PSTR("LAYR"), false);
    oled_write_char('0' + get_highest_layer(layer_state), false);
    oled_write_ln_P(PSTR(""), false);
    oled_write_ln_P(PSTR(""), false);
    led_t led = host_keyboard_led_state();
    oled_write_ln_P(PSTR("CAPS"), led.caps_lock);
}

static void render_wpm(void) {
    oled_write_ln_P(PSTR("nrsk"), false);
    oled_write_ln_P(PSTR(""), false);
    oled_write_ln_P(PSTR("WPM"), false);
    oled_write(get_u8_str(get_current_wpm(), ' '), false);
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        render_status();
    } else {
        render_wpm();
    }
    return false;
}
#endif
